export default {
	login: "Jesserc",
	id: 94083757,
	node_id: "U_kgDOBZuarQ",
	avatar_url: "https://avatars.githubusercontent.com/u/94083757?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/Jesserc",
	html_url: "https://github.com/Jesserc",
	followers_url: "https://api.github.com/users/Jesserc/followers",
	following_url: "https://api.github.com/users/Jesserc/following{/other_user}",
	gists_url: "https://api.github.com/users/Jesserc/gists{/gist_id}",
	starred_url: "https://api.github.com/users/Jesserc/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/Jesserc/subscriptions",
	organizations_url: "https://api.github.com/users/Jesserc/orgs",
	repos_url: "https://api.github.com/users/Jesserc/repos",
	events_url: "https://api.github.com/users/Jesserc/events{/privacy}",
	received_events_url: "https://api.github.com/users/Jesserc/received_events",
	type: "User",
	site_admin: false,
	name: "Jesse Raymond",
	company: null,
	blog: "",
	location: null,
	email: null,
	hireable: null,
	bio: "Frontend Developer | Reactjs | Sass",
	twitter_username: "jesserc_",
	public_repos: 26,
	public_gists: 0,
	followers: 3,
	following: 3,
	created_at: "2021-11-10T22:39:15Z",
	updated_at: "2022-03-08T06:02:42Z",
};
